"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
import sys
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
def str_to_bool(value):
    return value.lower() in ["true", "1", "yes"]
def str2bool(value):
    return str(value).lower() in ("true", "1", "yes")

def str2none(value):
    return None if value in ("None", "none", "", None) else value




CLOUD_ENV = os.getenv("CLOUD_ENV")
IS_TESTING = "test" in sys.argv

# Load local .env files when present. `override=False` means real environment
# variables (a Coolify dashboard, docker-compose `environment:`, or an exported
# shell var) ALWAYS take precedence — the files only fill in what the environment
# did not already provide. Loading them unconditionally fixes the failure mode
# where a process started with CLOUD_ENV="True" (e.g. the Docker CMD's celery
# worker) skipped the file entirely and came up with no REDIS_URL / S3 / DB
# config: Celery then fell back to redis://localhost and file saves hit S3 with
# Bucket=None. `.env.dev` is loaded first so it wins for local development.
# Single source of truth for local dev is the repo-root `.env` (one file shared
# with the Next.js frontend). Backend-local `.env.dev` / `.env` are still honored
# if present, for back-compat. `override=False` means real environment variables
# (Coolify, docker-compose) always win.
for _env_path in (BASE_DIR / ".env.dev", BASE_DIR / ".env", BASE_DIR.parent / ".env"):
    if _env_path.exists():
        load_dotenv(_env_path, override=False)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY") or "local-development-secret-key-change-before-production-2026"

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,testserver").split(",") if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    "https://portal.calarisolutions.com",
]


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_yasg',
    'drf_spectacular',
    'storages',
    'django_celery_beat',

    'Auth',
    'projects',
    'builds',
    'vectorstore',
    'a2p',
    'onboarding',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must be first
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# Accept BOTH naming conventions for the same setting: the S3_* names used in
# local .env.dev, and the AWS_* names set in the Coolify production dashboard.
# (Production had AWS_S3_BUCKET_NAME / AWS_ACCESS_KEY_ID set, but the code only
# read S3_*, so the bucket resolved empty and uploads fell back / 500'd.)
S3_ACCESS_KEY = os.getenv("S3_ACCESS_KEY") or os.getenv("AWS_ACCESS_KEY_ID")
S3_SECRET_KEY = os.getenv("S3_SECRET_KEY") or os.getenv("AWS_SECRET_ACCESS_KEY")
S3_BUCKET_NAME = (
    os.getenv("S3_BUCKET_NAME")
    or os.getenv("AWS_S3_BUCKET_NAME")
    or os.getenv("AWS_STORAGE_BUCKET_NAME")
)
# blank for AWS; set for S3-compatible
S3_ENDPOINT = os.getenv("S3_ENDPOINT") or os.getenv("AWS_S3_ENDPOINT") or os.getenv("AWS_S3_ENDPOINT_URL")
S3_REGION = (
    os.getenv("S3_REGION") or os.getenv("AWS_REGION") or os.getenv("AWS_S3_REGION_NAME") or "us-east-1"
)
S3_FILE_OVERWRITE = str2bool(os.getenv("S3_FILE_OVERWRITE", "False"))
S3_DEFAULT_ACL = str2none(os.getenv("S3_DEFAULT_ACL", None))
S3_QUERYSTRING_AUTH = str2bool(os.getenv("S3_QUERYSTRING_AUTH", "True"))


AWS_ACCESS_KEY_ID = S3_ACCESS_KEY
AWS_SECRET_ACCESS_KEY = S3_SECRET_KEY
AWS_STORAGE_BUCKET_NAME = S3_BUCKET_NAME
AWS_S3_ENDPOINT_URL = S3_ENDPOINT
AWS_S3_FILE_OVERWRITE = S3_FILE_OVERWRITE
AWS_DEFAULT_ACL = S3_DEFAULT_ACL
AWS_QUERYSTRING_AUTH = S3_QUERYSTRING_AUTH
AWS_S3_REGION_NAME = S3_REGION
AWS_S3_SIGNATURE_VERSION = 's3v4'
# Verify TLS certs by default. Only an S3-compatible endpoint with a self-signed
# cert (e.g. local MinIO) should opt out via S3_VERIFY=False — never disable it
# against real AWS/managed S3, which would expose uploads to MITM.
AWS_S3_VERIFY = str2bool(os.getenv("S3_VERIFY", "True"))

# Use S3 only when it is FULLY configured (bucket + access key + secret). A
# partial config (e.g. an empty S3_BUCKET_NAME, or keys without a bucket) must
# fall back to local storage rather than select the S3 backend with no bucket —
# that path makes every FileField save crash inside botocore with
# "expected string or bytes-like object, got 'NoneType'" (Bucket=None). Requiring
# all three keeps uploads working in dev and any env where S3 is not set up.
USE_S3 = bool(S3_BUCKET_NAME and S3_ACCESS_KEY and S3_SECRET_KEY)

if USE_S3:
    STORAGES = {
        "default": {"BACKEND": "config.storage.S3MediaStorage"},
        "staticfiles": {"BACKEND": "config.storage.S3StaticFilesStorage"},
    }
else:
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

# Local media (used by the FileSystemStorage fallback above; harmless under S3).
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# The Next.js frontend (its BFF) consumes this API. Allow its origin + credentials.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000").rstrip("/")
CORS_ALLOWED_ORIGINS = list({
    FRONTEND_URL,
    "http://localhost:3000",
    "http://127.0.0.1:3000",
})
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-csrftoken",
]
CSP_SCRIPT_SRC = tuple(
    s.strip() for s in os.getenv("CSP_SCRIPT_SRC", "'self'").split(",") if s.strip()
)



ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from urllib.parse import urlparse, unquote

# PostgreSQL. Prefer a single DATABASE_URL DSN; fall back to DB_* parts.
DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    _db = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (_db.path or '/postgres').lstrip('/') or 'postgres',
            'USER': unquote(_db.username or ''),
            'PASSWORD': unquote(_db.password or ''),
            'HOST': _db.hostname or '127.0.0.1',
            'PORT': str(_db.port or 5432),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv("DB_NAME", "postgres"),
            'USER': os.getenv("DB_USER", "postgres"),
            'PASSWORD': os.getenv("DB_PASSWORD", ""),
            'HOST': os.getenv("DB_HOST", "127.0.0.1"),
            'PORT': os.getenv("DB_PORT", "5432"),
        }
    }

# Reuse DB connections across requests — critical when the Postgres is remote,
# otherwise every request pays a fresh connect/TLS round-trip.
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

# ── Second database: pgvector store for semantic Build Library retrieval ──
# Optional. When VECTOR_DATABASE_URL is set, the `vectorstore` app (embeddings)
# lives here and retrieval goes semantic; otherwise it's absent and retrieval
# falls back to Postgres full-text search on the default DB. Kept separate because
# the main managed Postgres doesn't have the `vector` extension.
VECTOR_DATABASE_URL = os.getenv("VECTOR_DATABASE_URL")
VECTOR_DB_ALIAS = "vectors"
if VECTOR_DATABASE_URL:
    _vdb = urlparse(VECTOR_DATABASE_URL)
    DATABASES[VECTOR_DB_ALIAS] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': (_vdb.path or '/postgres').lstrip('/') or 'postgres',
        'USER': unquote(_vdb.username or ''),
        'PASSWORD': unquote(_vdb.password or ''),
        'HOST': _vdb.hostname or '127.0.0.1',
        'PORT': str(_vdb.port or 5432),
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }

DATABASE_ROUTERS = ["config.db_router.VectorRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'
USE_TZ = True

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

if S3_ENDPOINT and S3_BUCKET_NAME:
    STATIC_URL = f"{S3_ENDPOINT}/{S3_BUCKET_NAME}/static/"
elif S3_BUCKET_NAME:
    STATIC_URL = f"https://{S3_BUCKET_NAME}.s3.{S3_REGION}.amazonaws.com/static/"
else:
    STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Backend is API-only; no project static dirs (admin/DRF ship their own).
STATICFILES_DIRS = []

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    # Cookie settings
    'AUTH_COOKIE': 'access_token',
    'AUTH_COOKIE_REFRESH': 'refresh_token',
    'AUTH_COOKIE_HTTP_ONLY': True,
    'AUTH_COOKIE_SAMESITE': 'Lax',
    'AUTH_COOKIE_SECURE': str_to_bool(os.getenv('AUTH_COOKIE_SECURE', str((not DEBUG and not IS_TESTING)).lower())),
}

SESSION_COOKIE_SECURE = str_to_bool(os.getenv("SESSION_COOKIE_SECURE", str((not DEBUG and not IS_TESTING)).lower()))
CSRF_COOKIE_SECURE = str_to_bool(os.getenv("CSRF_COOKIE_SECURE", str((not DEBUG and not IS_TESTING)).lower()))
SECURE_SSL_REDIRECT = str_to_bool(os.getenv("SECURE_SSL_REDIRECT", str((not DEBUG and not IS_TESTING)).lower()))
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if (not DEBUG and not IS_TESTING) else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = str_to_bool(os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True"))
SECURE_HSTS_PRELOAD = str_to_bool(os.getenv("SECURE_HSTS_PRELOAD", str((not DEBUG and not IS_TESTING)).lower()))

# Default primary key field type 
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Auth.DashboardUser'

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'Auth.authentication.CookieJWTAuthentication',
    ),
    # Keep AllowAny as global default; individual viewsets declare their own permissions.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Cap list responses (frontend handles both arrays and {results}).
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
}

# ─── drf-spectacular (Swagger / OpenAPI) ───
SPECTACULAR_SETTINGS = {
    'TITLE': 'Calari Staff Portal API',
    'DESCRIPTION': 'REST API documentation for the Calari Staff Portal',
    'VERSION': 'v1',
    'CONTACT': {'email': 'support@calari.com'},
    'LICENSE': {'name': 'Proprietary'},
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/api/',
    'TAGS': [
        {'name': 'Auth — Token',           'description': 'Login, logout and token refresh'},
        {'name': 'Auth — Profile',         'description': 'Current user profile and password change'},
        {'name': 'Auth — User Management', 'description': 'CRUD operations on portal users (managers only)'},
        {'name': 'Auth — Password Reset',  'description': 'Self-service forgot / reset password flow'},
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
}

# class CustomTokenLifetime:
#     def __init__(self, user):
#         # 1 year for superusers, else 30 days
#         if user and user.is_superuser:
#             self.access = timedelta(days=365)
#             self.refresh = timedelta(days=365)
#         else:
#             self.access = timedelta(days=30)
#             self.refresh = timedelta(days=30)

# def custom_access_token_lifetime(user):
#     return CustomTokenLifetime(user).access

# def custom_refresh_token_lifetime(user):
#     return CustomTokenLifetime(user).refresh

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
#     'ROTATE_REFRESH_TOKENS': True,
#     'UPDATE_LAST_LOGIN': True,
#     'AUTH_HEADER_TYPES': ('Token',),
#     # Custom lifetime functions (requires custom JWT authentication class)
#     'ACCESS_TOKEN_LIFETIME_FUNC': custom_access_token_lifetime,
#     'REFRESH_TOKEN_LIFETIME_FUNC': custom_refresh_token_lifetime,
# }


# ─── Django Channels — Redis channel layer ───
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://localhost:6379/0')],
        },
    },
}

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')

# When no Celery worker is running (typical in dev), run tasks in-process so
# emails (notifications, etc.) are still sent. Set CELERY_ALWAYS_EAGER=False in
# production where a dedicated worker consumes the queue.
CELERY_TASK_ALWAYS_EAGER = str2bool(os.getenv('CELERY_ALWAYS_EAGER', 'True' if DEBUG else 'False'))
CELERY_TASK_EAGER_PROPAGATES = False

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = None
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = 'Africa/Nairobi'
BROKER_HEARTBEAT = 60
broker_connection_retry_on_startup = True
CELERY_BROKER_TRANSPORT_OPTIONS = {
    'confirm_publish': True,
    'connect_timeout': 5,
}
CELERY_BROKER_CONNECTION_TIMEOUT = 5



# EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
# EMAIL_HOST = os.getenv("EMAIL_HOST")
# EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))  # Convert to integer
# EMAIL_USE_TLS = str_to_bool(os.getenv("EMAIL_USE_TLS", "True"))  # Convert to boolean
# EMAIL_USE_SSL = str_to_bool(os.getenv("EMAIL_USE_SSL", "False"))  # Convert to boolean
# EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# Read the SMTP_* names (one set, shared with the Next.js frontend mailer);
# fall back to Django's EMAIL_* names for back-compat.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv("SMTP_HOST") or os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("SMTP_PORT") or os.getenv("EMAIL_PORT") or 587)
EMAIL_USE_TLS = str_to_bool(os.getenv("EMAIL_USE_TLS", "True"))
EMAIL_USE_SSL = str_to_bool(os.getenv("EMAIL_USE_SSL", "False"))
EMAIL_HOST_USER = os.getenv("SMTP_USER") or os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("SMTP_PASS") or os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("EMAIL_FROM") or os.getenv("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER

# Where new public A2P intake submissions are emailed (comma-separated). If unset,
# falls back to active admin/superuser emails.
A2P_NOTIFY_EMAILS = os.getenv("A2P_NOTIFY_EMAILS", "")

USE_HTTPS = os.getenv("USE_HTTPS", "False").lower() in ("true", "1")
SCHEME = "https" if USE_HTTPS else "http"
PORTAL_BASE_URL = f"{SCHEME}://{os.getenv('API_DOMAIN', 'localhost:8000')}"


SWAGGER_SETTINGS = {
    "DEFAULT_API_URL": f"{SCHEME}://{os.getenv('API_DOMAIN', 'localhost:8000')}",
    'DEFAULT_INFO': 'config.urls.schema_info',
    'SECURITY_DEFINITIONS': {
         'Token': {
            'type': 'apiKey',
            'in': 'header',
            'name': 'Authorization',
            'description': 'Enter format: Token <token> or Bearer <token>',
        }
    },
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',  # Using the 'verbose' formatter with timestamp
        },
        'worker_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'celery_worker.log',
            'formatter': 'verbose',  # Using the 'verbose' formatter with timestamp
        },
        'beat_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'celery_beat.log',
            'formatter': 'verbose',  # Using the 'verbose' formatter with timestamp
        },
    },
    'loggers': {
        'celery': {
            'handlers': ['console', 'worker_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery.beat': {
            'handlers': ['console', 'beat_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# ─── Error monitoring (Sentry) — env-gated, optional ───
# No-op unless SENTRY_DSN is set, and import-guarded so dev/CI without the package
# (it's installed in the Docker image, not the hash-pinned requirements) still run.
SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.celery import CeleryIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration(), CeleryIntegration()],
            traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0")),
            send_default_pii=False,
            environment=os.getenv("SENTRY_ENVIRONMENT", "development" if DEBUG else "production"),
        )
    except Exception:  # noqa: BLE001 — never let monitoring setup break boot
        pass
