# Generated by Django 5.2.15 on 2026-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_tasks_options_remove_tasks_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='ghl_location_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
