# Generated by Django 6.0.5 on 2026-08-27 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_clients_ghl_location_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhlConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=120)),
                ('encrypted_token', models.TextField()),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_check', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ghl_connection', to='projects.clients')),
            ],
        ),
    ]
