# Generated by Django 6.0.5 on 2026-08-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_ghlconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlconnection',
            name='business_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ghlconnection',
            name='location_id',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
