# Generated by Django 5.2.15 on 2026-06-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A2PSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_business_name', models.CharField(max_length=300)),
                ('dba_brand_name', models.CharField(blank=True, default='', max_length=300)),
                ('ein_tax_id', models.CharField(max_length=64)),
                ('business_type', models.CharField(max_length=120)),
                ('business_industry', models.CharField(max_length=120)),
                ('business_website', models.CharField(max_length=500)),
                ('business_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=32)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=64)),
                ('rep_first_name', models.CharField(max_length=120)),
                ('rep_last_name', models.CharField(max_length=120)),
                ('rep_email', models.EmailField(max_length=254)),
                ('rep_phone', models.CharField(max_length=64)),
                ('rep_job_title', models.CharField(max_length=120)),
                ('sms_use_case', models.CharField(max_length=200)),
                ('message_types', models.JSONField(default=list)),
                ('sms_program_description', models.TextField()),
                ('optin_method', models.CharField(max_length=120)),
                ('optin_form_url', models.CharField(blank=True, default='', max_length=500)),
                ('has_sms_consent_checkbox', models.CharField(max_length=16)),
                ('has_privacy_policy', models.CharField(max_length=16)),
                ('privacy_policy_url', models.CharField(blank=True, default='', max_length=500)),
                ('has_terms_of_service', models.CharField(max_length=16)),
                ('terms_of_service_url', models.CharField(blank=True, default='', max_length=500)),
                ('phone_numbers', models.JSONField(default=list)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('SUBMITTED', 'Submitted to registry'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='a2p_a2psubm_status_9903cd_idx')],
            },
        ),
    ]
