# Generated by Django 5.2.15 on 2026-06-26 22:18

import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Enable pgvector on the vectors DB before creating the vector column.
        VectorExtension(),
        migrations.CreateModel(
            name='BuildKnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_id', models.IntegerField(db_index=True)),
                ('client_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('chunk_index', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('use_for_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='bkc_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
