# Generated by Django 6.0.5 on 2026-08-27 15:09

from django.db import migrations, models


def populate_previews(apps, schema_editor):
    Run = apps.get_model('ghl_chat', 'Run')
    for run in Run.objects.using(schema_editor.connection.alias).all().iterator(chunk_size=25):
        Run.objects.using(schema_editor.connection.alias).filter(pk=run.pk).update(
            row_preview=run.rows[:100], row_count=len(run.rows),
            csv_available=bool(run.csv_data), pdf_available=bool(run.pdf))


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='csv_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='pdf_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='run',
            name='row_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='row_preview',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(populate_previews, migrations.RunPython.noop),
    ]
