# Generated by Django 5.2.15 on 2026-06-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsource',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='build',
            name='maintenance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='build',
            name='one_line_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='build',
            name='overview',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='entry_mechanism',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='entry_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_sources', to='builds.pipelinestage'),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='fires',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='handling_workflow',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='tags_applied',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='entry_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='is_automatic',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FIELD', 'Custom field'), ('VALUE', 'Custom value')], default='FIELD', max_length=8)),
                ('key', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('populated', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='builds.build')),
            ],
            options={
                'ordering': ['kind', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PreLaunchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('optional', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_launch_items', to='builds.build')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_label', models.CharField(blank=True, default='', max_length=255)),
                ('to_label', models.CharField(blank=True, default='', max_length=255)),
                ('trigger', models.TextField()),
                ('is_automatic', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='builds.build')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='builds.pipelinestage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='builds.pipelinestage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('meaning', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='builds.build')),
            ],
            options={
                'ordering': ['order', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('category', models.CharField(choices=[('ACTIVE_CONVERSION', 'Active conversion (A)'), ('INTAKE_ROUTING', 'Intake & routing (IN)'), ('RECORD_KEEPING', 'Record-keeping (REC)'), ('APPOINTMENT_LIFECYCLE', 'Appointment lifecycle (E, K)'), ('POST_VISIT', 'Post-visit & retention (G)'), ('INTERNAL_UTILITY', 'Internal & utility (H, X, Y, Z)'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('trigger', models.CharField(blank=True, default='', max_length=500)),
                ('what_it_does', models.TextField(blank=True, default='')),
                ('patient_facing', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='builds.build')),
            ],
            options={
                'ordering': ['category', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VisionGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OVERVIEW', 'Overview / big idea'), ('STAGE', 'Pipeline stage'), ('TRANSITION', 'Stage movement'), ('LEAD_SOURCE', 'Lead source'), ('WORKFLOW', 'Workflow'), ('CUSTOM_FIELD', 'Custom field / value'), ('TAG', 'Tag'), ('GENERAL', 'General')], default='GENERAL', max_length=16)),
                ('question', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=8)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ANSWERED', 'Answered'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=12)),
                ('answer', models.TextField(blank=True, default='')),
                ('created_by_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='builds.build')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-severity', 'created_at'],
                'indexes': [models.Index(fields=['build', 'status'], name='builds_visi_build_i_97ae19_idx')],
            },
        ),
    ]
