# Generated by Django 5.2.15 on 2026-06-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_alter_contactsource_options_build_maintenance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiongap',
            name='category',
            field=models.CharField(choices=[('OVERVIEW', 'Overview / big idea'), ('STAGE', 'Pipeline stage'), ('TRANSITION', 'Stage movement'), ('LEAD_SOURCE', 'Lead source'), ('CALENDAR', 'Calendar / booking'), ('INTEGRATION', 'Integration / data flow'), ('WORKFLOW', 'Workflow'), ('CUSTOM_FIELD', 'Custom field / value'), ('TAG', 'Tag'), ('GENERAL', 'General')], default='GENERAL', max_length=16),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ROUND_ROBIN', 'Round robin'), ('COLLECTIVE', 'Collective'), ('CLASS', 'Class / group'), ('SERVICE', 'Service'), ('PERSONAL', 'Personal'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('purpose', models.TextField(blank=True, default='')),
                ('booking_url', models.CharField(blank=True, default='', max_length=1000)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=500)),
                ('on_booking', models.TextField(blank=True, default='')),
                ('reminders', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('books_into_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_calendars', to='builds.pipelinestage')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='builds.build')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound (into GHL)'), ('OUTBOUND', 'Outbound (out of GHL)'), ('BIDIRECTIONAL', 'Bidirectional')], default='INBOUND', max_length=16)),
                ('mechanism', models.CharField(choices=[('API', 'API'), ('WEBHOOK', 'Webhook'), ('NATIVE', 'Native integration'), ('ZAPIER', 'Zapier / Make'), ('CRON', 'Scheduled sync (cron)'), ('OTHER', 'Other')], default='API', max_length=16)),
                ('data_objects', models.CharField(blank=True, default='', max_length=500)),
                ('purpose', models.TextField(blank=True, default='')),
                ('trigger_cadence', models.CharField(blank=True, default='', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', max_length=1000)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_integrations', to='builds.build')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
