# Generated by Django 5.2.15 on 2026-06-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_alter_visiongap_category_calendar_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='calendar',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactsource',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='customfield',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integration',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integration',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='integration',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='integration',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='ai_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pipelinestage',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prelaunchitem',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prelaunchitem',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='prelaunchitem',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prelaunchitem',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stagetransition',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tagdefinition',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='workflow',
            name='inferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workflow',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
