# Generated by Django 5.2.15 on 2026-06-26 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_calendar_ai_generated_calendar_confidence_and_more'),
        ('projects', '0003_alter_tasks_options_remove_tasks_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('filename', models.CharField(blank=True, default='', max_length=500)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('use_for_ai', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_docs', to='builds.build')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_docs', to='projects.clients')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['use_for_ai', 'client'], name='builds_buil_use_for_927cf2_idx')],
            },
        ),
    ]
