# Generated by Django 5.2.15 on 2026-06-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='memory_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='kind',
            field=models.CharField(choices=[('kickoff', 'Kickoff'), ('meeting', 'Meeting notes'), ('progress', 'Progress update'), ('change_request', 'Client-requested update'), ('other', 'Other')], default='meeting', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='meeting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingnote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
