# Generated by Django 5.2.15 on 2026-06-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_build_memory_summary_meetingnote_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='multi_pass',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AiGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(default='chat', max_length=32)),
                ('provider', models.CharField(blank=True, default='', max_length=16)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['op', 'created_at'], name='builds_aige_op_e7c801_idx'), models.Index(fields=['created_at'], name='builds_aige_created_d2aafb_idx')],
            },
        ),
    ]
