# Generated by Django 5.2.15 on 2026-06-27 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0009_aiconfig_multi_pass_aigenerationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSectionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('PIPELINE', 'Pipeline'), ('AUTOMATIONS', 'Automations'), ('LEAD_SOURCES', 'Lead sources'), ('CALENDARS', 'Calendars'), ('INTEGRATIONS', 'Integrations'), ('FIELDS_TAGS', 'Fields & tags'), ('FORMS_PAYMENTS', 'Forms & payments'), ('REPORTING_LAUNCH', 'Reporting & launch')], max_length=32)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], default='TODO', max_length=16)),
                ('blocker_note', models.TextField(blank=True, default='')),
                ('blocker_attachment_url', models.URLField(blank=True, default='', max_length=1000)),
                ('blocker_attachment_name', models.CharField(blank=True, default='', max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_build_sections', to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_reviews', to='builds.build')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_build_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section'],
                'indexes': [models.Index(fields=['build', 'status'], name='builds_buil_build_i_d00de4_idx')],
                'constraints': [models.UniqueConstraint(fields=('build', 'section'), name='unique_build_section_review')],
            },
        ),
    ]
