# Generated by Django 5.2.15 on 2026-06-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0010_buildsectionreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildsectionreview',
            name='section',
            field=models.CharField(choices=[('PIPELINE', 'Pipeline'), ('AUTOMATIONS', 'Automations'), ('CLIENT_UPDATES', 'New features & updates'), ('LEAD_SOURCES', 'Lead sources'), ('CALENDARS', 'Calendars'), ('INTEGRATIONS', 'Integrations'), ('FIELDS_TAGS', 'Fields & tags'), ('FORMS_PAYMENTS', 'Forms & payments'), ('REPORTING_LAUNCH', 'Reporting & launch')], max_length=32),
        ),
    ]
