# Generated by Django 5.2.15 on 2026-06-27 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0011_alter_buildsectionreview_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buildsectionreview',
            name='blocker_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='blocker_attachment_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='blocker_attachment_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='blocker_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='implementation_steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='implemented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='implemented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('IN_BUILD', 'In Build'), ('BLOCKED', 'Blocked'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected'), ('IMPLEMENTED', 'Implemented')], default='PENDING', max_length=16),
        ),
    ]
