# Generated by Django 5.2.15 on 2026-06-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0012_buildsectionreview_blocker_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='tasklist_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='MeetingActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('detail', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('REQUEST', 'Request / task'), ('CHANGE', 'Change to existing scope'), ('QUESTION', 'Open question'), ('DECISION', 'Decision made'), ('INFO', 'Info / note')], default='REQUEST', max_length=16)),
                ('section', models.CharField(blank=True, choices=[('PIPELINE', 'Pipeline'), ('AUTOMATIONS', 'Automations'), ('CLIENT_UPDATES', 'New features & updates'), ('LEAD_SOURCES', 'Lead sources'), ('CALENDARS', 'Calendars'), ('INTEGRATIONS', 'Integrations'), ('FIELDS_TAGS', 'Fields & tags'), ('FORMS_PAYMENTS', 'Forms & payments'), ('REPORTING_LAUNCH', 'Reporting & launch')], default='', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('DROPPED', 'Dropped')], default='OPEN', max_length=16)),
                ('superseded', models.BooleanField(default=False)),
                ('superseded_reason', models.TextField(blank=True, default='')),
                ('ai_generated', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='builds.build')),
                ('introduced_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_action_items', to='builds.meetingnote')),
                ('last_changed_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_action_items', to='builds.meetingnote')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['build', 'superseded'], name='builds_meet_build_i_2f3d5a_idx')],
            },
        ),
    ]
