# Generated by Django 5.2.15 on 2026-06-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0013_build_tasklist_status_meetingactionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsource',
            name='build',
        ),
        migrations.RemoveField(
            model_name='contactsource',
            name='entry_stage',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='build',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='build',
        ),
        migrations.RemoveField(
            model_name='manualaction',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='build',
        ),
        migrations.RemoveField(
            model_name='stagetransition',
            name='to_stage',
        ),
        migrations.RemoveField(
            model_name='stagetransition',
            name='from_stage',
        ),
        migrations.RemoveField(
            model_name='prelaunchitem',
            name='build',
        ),
        migrations.RemoveField(
            model_name='stagetransition',
            name='build',
        ),
        migrations.RemoveField(
            model_name='tagdefinition',
            name='build',
        ),
        migrations.RemoveField(
            model_name='visiongap',
            name='build',
        ),
        migrations.RemoveField(
            model_name='visiongap',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='build',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
        migrations.DeleteModel(
            name='ContactSource',
        ),
        migrations.DeleteModel(
            name='CustomField',
        ),
        migrations.DeleteModel(
            name='Integration',
        ),
        migrations.DeleteModel(
            name='ManualAction',
        ),
        migrations.DeleteModel(
            name='PipelineStage',
        ),
        migrations.DeleteModel(
            name='PreLaunchItem',
        ),
        migrations.DeleteModel(
            name='StageTransition',
        ),
        migrations.DeleteModel(
            name='TagDefinition',
        ),
        migrations.DeleteModel(
            name='VisionGap',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
    ]
