# Generated by Django 5.2.15 on 2026-06-27 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0014_remove_contactsource_build_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingactionitem',
            name='evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meetingactionitem',
            name='verification',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified'), ('NEEDS_INFO', 'Needs info')], default='UNVERIFIED', max_length=12),
        ),
        migrations.AddField(
            model_name='meetingactionitem',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='paste', max_length=32)),
                ('raw_text', models.TextField()),
                ('file_url', models.URLField(blank=True, default='', max_length=1000)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('ai_output', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('pushback', models.JSONField(blank=True, default=list)),
                ('verified_count', models.IntegerField(default=0)),
                ('needs_info_count', models.IntegerField(default=0)),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='builds.build')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
