# Generated by Django 5.2.15 on 2026-06-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0015_meetingactionitem_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
