# Generated by Django 5.2.15 on 2026-06-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0016_notificationpreference_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='build_document',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='build',
            name='build_document_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
