# Generated by Django 5.2.15 on 2026-06-27 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0017_build_build_document_build_build_document_at'),
        ('projects', '0003_alter_tasks_options_remove_tasks_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buildknowledge',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildknowledge',
            name='build_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='buildknowledge',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buildknowledge',
            name='ghl_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='buildknowledge',
            name='integrations',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='buildknowledge',
            name='niche',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='buildknowledge',
            name='quality',
            field=models.CharField(choices=[('GOLD', 'Gold (approved build)'), ('STANDARD', 'Standard'), ('RAW', 'Raw')], default='STANDARD', max_length=12),
        ),
        migrations.AddIndex(
            model_name='buildknowledge',
            index=models.Index(fields=['use_for_ai', 'quality'], name='builds_buil_use_for_243b19_idx'),
        ),
    ]
