# Generated by Django 5.2.15 on 2026-07-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0018_buildknowledge_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='ghl_mcp_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='ghl_mcp_token_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='ghl_mcp_token_preview',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='ghl_mcp_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
