# Generated by Django 6.0.5 on 2026-08-27 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0019_aiconfig_ghl_mcp_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_build_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=8),
        ),
        migrations.AddField(
            model_name='task',
            name='source_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task', to='builds.meetingactionitem'),
        ),
        migrations.AlterField(
            model_name='buildsectionreview',
            name='section',
            field=models.CharField(choices=[('FUNNELS', 'Funnels'), ('EMAIL_COPY', 'Email copy'), ('PIPELINE', 'Pipeline'), ('AUTOMATIONS', 'Automations'), ('CLIENT_UPDATES', 'New features & updates'), ('LEAD_SOURCES', 'Lead sources'), ('CALENDARS', 'Calendars'), ('INTEGRATIONS', 'Integrations'), ('FIELDS_TAGS', 'Fields & tags'), ('FORMS_PAYMENTS', 'Forms & payments'), ('REPORTING_LAUNCH', 'Reporting & launch')], max_length=32),
        ),
        migrations.AlterField(
            model_name='meetingactionitem',
            name='section',
            field=models.CharField(blank=True, choices=[('FUNNELS', 'Funnels'), ('EMAIL_COPY', 'Email copy'), ('PIPELINE', 'Pipeline'), ('AUTOMATIONS', 'Automations'), ('CLIENT_UPDATES', 'New features & updates'), ('LEAD_SOURCES', 'Lead sources'), ('CALENDARS', 'Calendars'), ('INTEGRATIONS', 'Integrations'), ('FIELDS_TAGS', 'Fields & tags'), ('FORMS_PAYMENTS', 'Forms & payments'), ('REPORTING_LAUNCH', 'Reporting & launch')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='builds.build'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('AUTOMATION', 'Automation'), ('PIPELINE', 'Pipeline'), ('TAG', 'Tags'), ('EMAIL', 'Email copy'), ('FUNNEL', 'Funnel'), ('FORM', 'Form'), ('INTEGRATION', 'Integration'), ('OTHER', 'Other')], default='OTHER', max_length=16),
        ),
    ]
