# Generated by Django 6.0.5 on 2026-08-27 11:25

from django.db import migrations


def archive_feedback(apps, schema_editor):
    """Preserve submitted feedback in the internal history before retiring its table."""
    feedback = apps.get_model("builds", "ClientPortalFeedback")
    activity = apps.get_model("builds", "Activity")
    alias = schema_editor.connection.alias
    batch = []
    for row in feedback.objects.using(alias).order_by("id").iterator(chunk_size=500):
        batch.append(activity(build_id=row.build_id, actor="Archived client feedback", message=f"Feedback received {row.created_at.isoformat()} from {row.name or 'Client'}:\n{row.message}"))
        if len(batch) == 500:
            activity.objects.using(alias).bulk_create(batch)
            batch = []
    if batch:
        activity.objects.using(alias).bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0020_task_creator_task_priority_task_source_item_and_more'),
    ]

    operations = [
        migrations.RunPython(archive_feedback, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='clientportalfeedback',
            name='builds_clie_build_i_456039_idx',
        ),
        migrations.RemoveField(
            model_name='build',
            name='client_portal_enabled',
        ),
        migrations.RemoveField(
            model_name='build',
            name='client_portal_token',
        ),
        migrations.DeleteModel(
            name='ClientPortalFeedback',
        ),
    ]
