# Generated by Django 6.0.5 on 2026-08-27 11:34

from django.db import migrations, models


def retire_unsupported_providers(apps, schema_editor):
    supported = ["OPENAI", "ANTHROPIC"]
    alias = schema_editor.connection.alias
    # Retain encrypted credentials for recovery; removed providers cannot be
    # listed, activated, or selected through the current API/runtime.
    apps.get_model("builds", "AiApiKey").objects.using(alias).exclude(provider__in=supported).update(active=False)
    apps.get_model("builds", "AiConfig").objects.using(alias).exclude(provider__in=supported).update(
        provider="OPENAI", model="", blueprint_model="",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0021_remove_client_portal'),
    ]

    operations = [
        migrations.RunPython(retire_unsupported_providers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='aiapikey',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic Claude')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic Claude')], default='OPENAI', max_length=16),
        ),
    ]
