# Generated by Django 6.0.5 on 2026-08-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0022_limit_ai_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiconfig',
            name='ghl_mcp_model',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='ghl_mcp_token_encrypted',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='ghl_mcp_token_preview',
        ),
        migrations.RemoveField(
            model_name='aiconfig',
            name='ghl_mcp_url',
        ),
    ]
