# Generated by Django 6.0.5 on 2026-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0023_remove_aiconfig_ghl_mcp_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ghl_verification_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ghl_verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='ghl_verification_revision',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ghl_verification_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ghl_verification_status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=24),
        ),
    ]
