# Generated by Django 6.0.5 on 2026-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0024_task_ghl_verification_checked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ghl_acceptance_checks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
