# Generated by Django 5.2.15 on 2026-06-27 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_tasks_options_remove_tasks_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireflies_call_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('call_date', models.DateTimeField(blank=True, null=True)),
                ('participants', models.JSONField(blank=True, default=list)),
                ('transcript_url', models.URLField(blank=True, default='', max_length=1000)),
                ('summary', models.TextField(blank=True, default='')),
                ('insight', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('distributed', 'Distributed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('raw_transcript', models.TextField(blank=True, default='')),
                ('ai_model', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_insights', to='projects.clients')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('FIREFLIES', 'Fireflies'), ('ASANA', 'Asana'), ('SLACK', 'Slack'), ('GDRIVE', 'Google Drive')], max_length=16)),
                ('auth_type', models.CharField(choices=[('api_key', 'API key'), ('oauth', 'OAuth')], default='api_key', max_length=8)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('encrypted_secret', models.TextField()),
                ('secret_preview', models.CharField(blank=True, default='', max_length=64)),
                ('encrypted_refresh', models.TextField(blank=True, default='')),
                ('scopes', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('workspace_ref', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('ASANA', 'Asana tasks'), ('SLACK_INTERNAL', 'Slack (internal)'), ('SLACK_EXTERNAL', 'Slack (external)'), ('DRIVE', 'Google Drive doc')], max_length=16)),
                ('dedupe_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retracted', 'Retracted')], default='pending', max_length=12)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('payload_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='onboarding.callinsight')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(blank=True, default='', max_length=32)),
                ('drive_folder_id', models.CharField(blank=True, default='', max_length=255)),
                ('drive_onboarding_doc_id', models.CharField(blank=True, default='', max_length=255)),
                ('asana_project_gid', models.CharField(blank=True, default='', max_length=64)),
                ('slack_internal_channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('slack_external_channel_id', models.CharField(blank=True, default='', max_length=64)),
                ('match_domains', models.TextField(blank=True, default='')),
                ('match_emails', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_map', to='projects.clients')),
            ],
            options={
                'ordering': ['client_number', 'client_id'],
            },
        ),
        migrations.AddIndex(
            model_name='callinsight',
            index=models.Index(fields=['client', 'status'], name='onboarding__client__4bbbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['provider', 'active'], name='onboarding__provide_ac6d83_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['call_insight', 'target'], name='onboarding__call_in_e44a83_idx'),
        ),
    ]
