# Generated by Django 6.0.5 on 2026-08-27 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0020_task_creator_task_priority_task_source_item_and_more'),
        ('onboarding', '0002_automationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='FathomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('encrypted_webhook_secret', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FathomRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fathom_rules', to='builds.build')),
            ],
            options={
                'ordering': ['participant_email'],
            },
        ),
        migrations.CreateModel(
            name='FathomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_id', models.CharField(max_length=64, unique=True)),
                ('webhook_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('recording_url', models.URLField(blank=True, default='', max_length=1000)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('participant_emails', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True, default='')),
                ('transcript', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Needs routing'), ('attached', 'Added to build'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('routing_reason', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fathom_meeting', to='builds.meetingnote')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['status', '-received_at'], name='onboarding__status_4c815b_idx')],
            },
        ),
    ]
