# Generated by Django 6.0.5 on 2026-08-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0020_task_creator_task_priority_task_source_item_and_more'),
        ('onboarding', '0003_fathomsettings_fathomroutingrule_fathommeeting'),
        ('projects', '0004_clients_ghl_location_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackIntakeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=32)),
                ('clare_user_id', models.CharField(blank=True, default='', max_length=32)),
                ('encrypted_signing_secret', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='automationsettings',
            name='external_posting_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('lease_token', models.CharField(blank=True, default='', max_length=36)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.clients')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SlackIntakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('message_ts', models.CharField(max_length=32)),
                ('thread_ts', models.CharField(max_length=32)),
                ('sender_id', models.CharField(max_length=32)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Awaiting analysis'), ('needs_setup', 'Routing setup needed'), ('routed', 'Assigned'), ('ignored', 'No action')], default='pending', max_length=12)),
                ('analysis', models.JSONField(default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='onboarding.slackchannel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SlackResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTOMATION', 'Automation'), ('PIPELINE', 'Pipeline'), ('TAG', 'Tags'), ('EMAIL', 'Email copy'), ('FUNNEL', 'Funnel'), ('FORM', 'Form'), ('INTEGRATION', 'Integration'), ('OTHER', 'Other')], max_length=16)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibilities', to='onboarding.slackchannel')),
            ],
        ),
        migrations.CreateModel(
            name='SlackTaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
                ('kind', models.CharField(max_length=16)),
                ('interpretation', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onboarding.slackintakeevent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_messages', to='builds.task')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SlackWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='onboarding.slackintakeevent')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='slack_work_item', to='builds.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='slackintakeevent',
            index=models.Index(fields=['status', 'id'], name='onboarding__status_df456e_idx'),
        ),
        migrations.AddIndex(
            model_name='slackintakeevent',
            index=models.Index(fields=['channel', 'thread_ts', 'id'], name='onboarding__channel_b36a4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='slackintakeevent',
            constraint=models.UniqueConstraint(fields=('channel', 'message_ts'), name='slack_message_once'),
        ),
        migrations.AddConstraint(
            model_name='slackresponsibility',
            constraint=models.UniqueConstraint(fields=('channel', 'category'), name='slack_channel_category_owner'),
        ),
        migrations.AddConstraint(
            model_name='slacktaskmessage',
            constraint=models.UniqueConstraint(fields=('event', 'category'), name='slack_task_message_once'),
        ),
        migrations.AddConstraint(
            model_name='slackworkitem',
            constraint=models.UniqueConstraint(fields=('event', 'category'), name='slack_event_category_once'),
        ),
    ]
