# Generated by Django 6.0.5 on 2026-08-27 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0024_task_ghl_verification_checked_at_and_more'),
        ('onboarding', '0004_slackintakesettings_and_more'),
        ('projects', '0006_ghlconnection_business_details_alter_clients_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slackchannel',
            name='context_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackchannel',
            name='context_revision',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='slackintakeevent',
            name='redacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slackintakeevent',
            name='source_revision',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='slackintakeevent',
            name='source_updated_ts',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='ClientInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=80)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.JSONField(default=dict)),
                ('record_reference', models.CharField(blank=True, default='', max_length=120)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(db_index=True, null=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='onboarding.slackchannel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.clients')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('source', models.CharField(max_length=16)),
                ('reference', models.CharField(max_length=160)),
                ('observation', models.JSONField(default=dict)),
                ('completeness', models.CharField(default='partial', max_length=16)),
                ('sensitivity', models.CharField(default='internal', max_length=16)),
                ('retrieved_at', models.DateTimeField()),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='onboarding.clientinvestigation')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('allow_record_reads', models.BooleanField(default=False)),
                ('retention_days', models.PositiveSmallIntegerField(default=30)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('lease_token', models.UUIDField(editable=False, null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.clients')),
            ],
        ),
        migrations.CreateModel(
            name='SlackContextGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(max_length=32)),
                ('slack_user_id', models.CharField(max_length=32)),
                ('encrypted_token', models.TextField()),
                ('encrypted_refresh', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(null=True)),
                ('scopes', models.JSONField(default=list)),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('active', models.BooleanField(default=True)),
                ('capabilities', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SlackOAuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=64, unique=True)),
                ('encrypted_verifier', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
                ('content', models.JSONField(default=dict)),
                ('generated_revision', models.UUIDField(null=True)),
                ('draft_text', models.TextField(blank=True, default='')),
                ('draft_version', models.PositiveIntegerField(default=0)),
                ('draft_edited', models.BooleanField(default=False)),
                ('draft_ready', models.BooleanField(default=False)),
                ('draft_stale', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='onboarding.clientinvestigation')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_brief', to='builds.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='clientinvestigation',
            index=models.Index(fields=['status', 'queued_at'], name='onboarding__status_ba997f_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientinvestigation',
            constraint=models.UniqueConstraint(fields=('client', 'source_key'), name='investigation_client_source'),
        ),
        migrations.AddConstraint(
            model_name='investigationevidence',
            constraint=models.UniqueConstraint(fields=('investigation', 'key'), name='investigation_evidence_key'),
        ),
    ]
