# Generated by Django 6.0.5 on 2026-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_slackchannel_context_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackcontextgrant',
            name='refresh_lease',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='slackcontextgrant',
            name='refresh_lease_until',
            field=models.DateTimeField(null=True),
        ),
    ]
