# Generated by Django 6.0.5 on 2026-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
