# Generated by Django 6.0.5 on 2026-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_alter_dashboarduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('employee', 'Employee'), ('finance', 'Finance')], default='employee', max_length=20),
        ),
    ]
