# Generated by Django 5.2.15 on 2026-06-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_dashboarduser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='feature_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
